version: "3.3"
services:
  db:
    image: postgres:14
    container_name: db
    volumes:
      - db_volume:/var/lib/postgresql/data:cached
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123qwe123qwe
      POSTGRES_DB: db_development

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    container_name: web
    volumes:
      - .:/app
    environment:
      RABBITMQ_HOST: rabbitmq
    ports:
      - "3000:3000"
    depends_on:
      - db
      - rabbitmq
      - redis
    links:
      - rabbitmq

  webpacker:
    build: .
    container_name: webpacker
    command: bin/webpack-dev-server
    volumes:
      - .:/app
    ports:
      - "3035:3035"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:3.2
    container_name: redis
    ports:
      - 6379:6379

volumes:
  db_volume:

networks:
  default:
    external:
      name: charlist_project_general