version: "3.3"
services:
  db:
    image: postgres:14
    volumes:
      - ./tmp/db:/var/lib/postgresql/data:cached
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123qwe123qwe
      POSTGRES_DB: db_development

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    environment:
      RABBITMQ_HOST: rabbitmq
    ports:
      - "3000:3000"
    depends_on:
      - db
      - rabbitmq
      - redis
    links:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:3.2
    ports:
      - 6379:6379
