default: &default
  adapter: postgresql
  encoding: unicode
  pool: 50
  username: postgres
  password: 123qwe123qwe
  host: db

development:
  <<: *default
  database: db_development

test:
  <<: *default
  database: db_test