development:
  adapter: postgresql
  encoding: unicode
  database: db_development
  pool: 50
  username: postgres
  password: 123qwe123qwe

test:
  adapter: postgresql
  encoding: unicode
  database: db_test
  pool: 5
  username: postgres
  password: 123qwe123qwe